In [5]:
import numpy as np
import torch
from torch.utils import data
from d2l import torch as d2l

In [6]:
true_w = torch.tensor([2, -3.4])
true_b = 4.2
features, labels = d2l.synthetic_data(true_w, true_b, 1000)

In [7]:
def load_array(data_arrays, batch_size, is_train=True):
    dataset = data.TensorDataset(*data_arrays)
    return data.DataLoader(dataset, batch_size, shuffle=is_train)

batch_size = 16
data_iter = load_array(features, batch_size, is_train=True)

In [8]:
next(iter(data_iter))

[tensor([-0.0679, -1.0622]),
 tensor([-0.4724, -0.7681]),
 tensor([ 0.9875, -0.6360]),
 tensor([-1.0461, -1.3068]),
 tensor([-0.4434, -1.2232]),
 tensor([-1.2664, -0.5801]),
 tensor([-0.3134, -0.1164]),
 tensor([-0.1447, -0.0118]),
 tensor([-1.2605, -0.3150]),
 tensor([-0.6487, -0.2510]),
 tensor([ 0.1408, -0.8209]),
 tensor([ 1.4949, -0.1333]),
 tensor([-0.3153, -0.2486]),
 tensor([ 0.4771, -0.0771]),
 tensor([2.8731, 1.1705]),
 tensor([ 0.3899, -0.9651]),
 tensor([0.2619, 0.6643]),
 tensor([0.5064, 1.4033]),
 tensor([1.1535, 0.5609]),
 tensor([-0.1816, -0.6657]),
 tensor([-0.0760,  1.4810]),
 tensor([-0.4332, -1.5523]),
 tensor([-0.4528, -0.4907]),
 tensor([-0.2357,  1.0514]),
 tensor([-0.6974,  0.1272]),
 tensor([0.6890, 1.0837]),
 tensor([1.2502, 0.6801]),
 tensor([-1.3815, -0.5588]),
 tensor([ 0.3271, -0.5449]),
 tensor([ 0.6536, -0.0967]),
 tensor([-0.9829, -0.2111]),
 tensor([0.9905, 1.1903]),
 tensor([0.9028, 1.7156]),
 tensor([-0.5281,  0.9248]),
 tensor([-0.7833,  0.3562]),
 

In [9]:
# nn是神经网络的缩写
from torch import nn

net = nn.Sequential(nn.Linear(2, 1))

In [10]:
net[0].weight.data.normal_(0, 0.01)
net[0].bias.data.fill_(0)

tensor([0.])

In [11]:
loss = nn.MSELoss()

In [12]:
trainer = torch.optim.SGD(net.parameters(), lr=0.03)

In [13]:
num_epochs = 3
for epoch in range(num_epochs):
    for X, y in data_iter:
        l = loss(net(X) ,y)
        trainer.zero_grad()
        l.backward()
        trainer.step()
    l = loss(net(features), labels)
    print(f'epoch {epoch + 1}, loss {l:f}')

ValueError: too many values to unpack (expected 2)